# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Vector Service (tipg)
  - package-ecosystem: pip
    directory: "/lib/tipg-api/runtime"
    schedule:
      interval: weekly

  # Raster Service (titiler-pgstac)
  - package-ecosystem: pip
    directory: "/lib/titiler-pgstac-api/runtime"
    schedule:
      interval: weekly

  # STAC Service (stac-fastapi)
  - package-ecosystem: pip
    directory: "/lib/stac-api/runtime"
    schedule:
      interval: weekly
    groups:
      stac_fastapi:
        patterns:
          - stac-fastapi*
