name: Build & try to release

on:
  push:

jobs:
  package:
    uses: ./.github/workflows/build.yaml
    with:
      release: true
    secrets:
      DS_RELEASE_BOT_ID: ${{ secrets.DS_RELEASE_BOT_ID }}
      DS_RELEASE_BOT_PRIVATE_KEY: ${{ secrets.DS_RELEASE_BOT_PRIVATE_KEY }}
