name: Deploy & Integration Test

permissions:
  id-token: write  # required for requesting the JWT
  contents: read  # required for actions/checkout

on:
  workflow_call:

  workflow_dispatch:
  
  # remove later
  # push:
  #   branches:
  #     - "feat/add-integration-tests"
    
jobs:
  deploy-and-integration-test:
    name: Deploy & Integration Test
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION_DEPLOY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEPLOY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEPLOY }}


    steps:

    - name: Checkout repository # for runs after `Distribute`, pulling from main will always give the latest eoapi-cdk. 
      uses: actions/checkout@v3

    - name: Set up python
      uses: actions/setup-python@v2
      with:
        cache: pip

    - name: Set up node
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Download compiled eoapi-cdk artifact
      uses: actions/download-artifact@v3
      with:
        name: python
        path: dist
  
    - name: Install eoapi-cdk from artifact
      run: pip install dist/python/*.gz
    
    - name: Install deployment environment
      working-directory: integration_tests/cdk
      run: |
        python -m venv .deployment_venv
        source .deployment_venv/bin/activate
        pip install -r requirements.txt
        npm install
        deactivate

    - name: Synthesize the stack
      working-directory: integration_tests/cdk
      run: |
        source .deployment_venv/bin/activate
        npx cdk synth --debug --all --require-approval never
        deactivate

    # deploys and grabs URLs from the output for later tests
    - name: Deploy the stack
      id: deploy_step
      working-directory: integration_tests/cdk
      run: |
        source .deployment_venv/bin/activate
        npx cdk deploy --ci --all --require-approval never
        echo "ingestor_url=$(aws cloudformation describe-stacks --stack-name eoapi-template-demo-test-pgSTAC-infra --query "Stacks[0].Outputs[?starts_with(OutputKey, 'stacingestor')].OutputValue | [0]" --output text)" >> $GITHUB_OUTPUT
        echo "stac_api_url=$(aws cloudformation describe-stacks --stack-name eoapi-template-demo-test-pgSTAC-infra --query "Stacks[0].Outputs[?starts_with(OutputKey, 'pgstacapi')].OutputValue | [0]" --output text)" >> $GITHUB_OUTPUT
        echo "titiler_pgstac_api_url=$(aws cloudformation describe-stacks --stack-name eoapi-template-demo-test-pgSTAC-infra --query "Stacks[0].Outputs[?starts_with(OutputKey, 'titilerpgstac')].OutputValue | [0]" --output text)" >> $GITHUB_OUTPUT
        deactivate

    - name: Install test environment
      working-directory: integration_tests/tests
      run: |
        python -m venv .tests_venv
        source .tests_venv/bin/activate
        pip install -e .
        deactivate

    - name: Test the stack
      working-directory: integration_tests/tests
      env:
        ingestor_url: ${{ steps.deploy_step.outputs.ingestor_url }}
        stac_api_url: ${{ steps.deploy_step.outputs.stac_api_url }}
        titiler_pgstac_api_url: ${{ steps.deploy_step.outputs.titiler_pgstac_api_url }}
      run: |
        source .tests_venv/bin/activate
        pytest eoapi_tests
        deactivate

    - name: Always tear down the stack
      if: always()
      working-directory: integration_tests/cdk
      run: |
        source .deployment_venv/bin/activate
        npx cdk destroy --ci --all --force
        deactivate
