name: Unit tests

on:
  workflow_dispatch:
  push:
    branches:
    - main
    tags:
    - 'v*'
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.7.*"
          enable-cache: true

      - name: Install PostgreSQL and PostGIS
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql postgresql-contrib postgresql-16-postgis-3
          sudo service postgresql start
          pg_isready

      - name: Install dependencies
        run: |
          uv sync

      - name: Run tests
        run: uv run pytest
